version: '3.6'

services:
  postgres:
    container_name: expy_db
    image:  postgres:11.2-alpine
    restart: always
    volumes:
      - expy:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "expy"
      POSTGRES_DB: "expy-db"
      POSTGRES_USER: "expy"
      PGDATA: /var/lib/postgresql/data/some_name/
  expy:
    container_name: expy_worker
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:   # Binds volume to enable working through docker locally
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
      - type: bind
        source: ./prisma/
        target: /app/prisma/
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment: 
      PORT: 3000
      ACCESS_TOKEN: "secret"
      NODE_ENV: "local"
volumes:
    expy: